"""add first_name last_name to users

Revision ID: 9ab6193e7a5a
Revises: 3283b8964173
Create Date: 2025-08-25 12:06:20.663482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab6193e7a5a'
down_revision: Union[str, None] = '3283b8964173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('otp_codes', 'phone',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.alter_column('otp_codes', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
